[package]
name = "rs-ffmpeg"
version = "0.1.0"
edition = "2021"
build   = "build.rs"

[dependencies]
libc     = "0.2"
log = "0.4"
chrono = "0.4.19"
pretty_env_logger = "0.4.0"

[build-dependencies]
cc = "1.0"
regex = "1.5"
bindgen = "0.59"
