[package]
name = "rs-ffmpeg"
version = "0.1.0"
edition = "2021"
build   = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc     = "0.2"

[build-dependencies]
cc = "1.0"
regex = "1.5"
bindgen = "0.59"
